import { useRouter } from "next/router";
import React, { useEffect, useState } from "react";
import { deletePayoutId, showIdData } from "../../service/api/payout";
import { Button } from "primereact/button";
import { Dialog } from "primereact/dialog";
import { updateReferralsLink } from "../../service/api/referrals";

const Edit = () => {
  const router = useRouter();
  const { id } = router.query;
  const [data, setData] = useState({});
  const [deleteDialog, setDeleteDialog] = useState(false);

  const getData = () => {
    showIdData(id)
      .then((data) => setData(data))
      .catch((err) => console.log(err));
  };
  useEffect(() => {
    getData();
  }, []);

  const deleteRefferals = () => {
    let ids = Array(id)
    deletePayoutId({ids}).then((res)=>{
        setDeleteDialog(false)
        router.push('/payouts')
    }).catch((err)=>{
        console.log(err);
    })
  }

  const deleteDialogFooter = (
    <React.Fragment>
      <Button
        label="No"
        icon="pi pi-times"
        outlined
        onClick={() => setDeleteDialog(false)}
      />
      <Button
        label="Yes"
        icon="pi pi-check"
        severity="danger"
        onClick={deleteRefferals}
      />
    </React.Fragment>
  );

  const unPaid = () => {
    let status = "Unpaid"
    updateReferralsLink({id,status}).then((res)=>{
        router.push('/payouts')
    }).catch((err)=>{
        console.log(err);
    })
  }

  return (
    <>
      <div className="card flex">
        <div className="w-14rem">
          <div>Affiliate</div>
          <div className="mt-5">Amount</div>
          <div className="mt-5">Generated By</div>
          <div className="mt-5">Payout Method</div>
          <div className="mt-5">Payout Account</div>
          <div className="mt-5">Invoice Link</div>
          <div className="mt-5">Status</div>
          <div className="mt-5">Description</div>
          <div className="mt-5">Payout Date</div>
          
        </div>

        <div className="w-full">
          <div>
            <a href="">{data.email}</a>
          </div>
          <div className="mt-5">{data.amount}</div>
          <div className="mt-5">Admin</div>
          <div className="mt-5">Payout Method</div>
          <div className="mt-5">Manual</div>
          <div className="mt-5">(none)</div>
          <div className="mt-5">{data.status}</div>
          <div className="mt-5">{data.description}</div>
          <div className="mt-5">{new Date(data.createAt).toLocaleString()}</div>
          <div className="mt-5 flex justify-content-end column-gap-3">
            <div><Button onClick={unPaid}>Mark as Unpaid</Button></div>
            <div><Button onClick={()=>setDeleteDialog(true)} severity="danger">Delete</Button></div>
          </div>
        </div>
      </div>
      <Dialog
        visible={deleteDialog}
        style={{ width: "32rem" }}
        breakpoints={{ "960px": "75vw", "641px": "90vw" }}
        header="Confirm"
        modal
        footer={deleteDialogFooter}
        onHide={() => setDeleteDialog(false)}
      >
        <div className="confirmation-content">
          <i
            className="pi pi-exclamation-triangle mr-3"
            style={{ fontSize: "2rem" }}
          />
          <span>Are you sure you want to delete?</span>
        </div>
      </Dialog>
    </>
  );
};

Edit.getInitialProps = async () => {
  // You can set the value for pageTitle in getInitialProps
  return { pageTitle: { url: "/payouts/id", name: "View Payout" } };
};

export default Edit;
